/*
 * system.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProtobufAny'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProtobufAny'));
  } else {
    // Browser globals (root is window)
    if (!root.Systemproto) {
      root.Systemproto = {};
    }
    root.Systemproto.RpcStatus = factory(root.Systemproto.ApiClient, root.Systemproto.ProtobufAny);
  }
}(this, function(ApiClient, ProtobufAny) {
  'use strict';

  /**
   * The RpcStatus model module.
   * @module model/RpcStatus
   * @version version not set
   */

  /**
   * Constructs a new <code>RpcStatus</code>.
   * @alias module:model/RpcStatus
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RpcStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RpcStatus} obj Optional instance to populate.
   * @return {module:model/RpcStatus} The populated <code>RpcStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('details'))
        obj.details = ApiClient.convertToType(data['details'], [ProtobufAny]);
    }
    return obj;
  }

  /**
   * @member {Number} code
   */
  exports.prototype.code = undefined;

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {Array.<module:model/ProtobufAny>} details
   */
  exports.prototype.details = undefined;


  return exports;

}));
