/*
 * system.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProtobufAny', 'model/RpcStatus', 'model/V1Organization', 'model/V1User', 'api/OrganizationServiceApi', 'api/UserServiceApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ProtobufAny'), require('./model/RpcStatus'), require('./model/V1Organization'), require('./model/V1User'), require('./api/OrganizationServiceApi'), require('./api/UserServiceApi'));
  }
}(function(ApiClient, ProtobufAny, RpcStatus, V1Organization, V1User, OrganizationServiceApi, UserServiceApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Systemproto = require('index'); // See note below*.
   * var xxxSvc = new Systemproto.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Systemproto.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Systemproto.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Systemproto.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version version not set
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ProtobufAny model constructor.
     * @property {module:model/ProtobufAny}
     */
    ProtobufAny: ProtobufAny,
    /**
     * The RpcStatus model constructor.
     * @property {module:model/RpcStatus}
     */
    RpcStatus: RpcStatus,
    /**
     * The V1Organization model constructor.
     * @property {module:model/V1Organization}
     */
    V1Organization: V1Organization,
    /**
     * The V1User model constructor.
     * @property {module:model/V1User}
     */
    V1User: V1User,
    /**
     * The OrganizationServiceApi service constructor.
     * @property {module:api/OrganizationServiceApi}
     */
    OrganizationServiceApi: OrganizationServiceApi,
    /**
     * The UserServiceApi service constructor.
     * @property {module:api/UserServiceApi}
     */
    UserServiceApi: UserServiceApi
  };

  return exports;
}));
