/*
 * system.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Systemproto);
  }
}(this, function(expect, Systemproto) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Systemproto.OrganizationServiceApi();
  });

  describe('(package)', function() {
    describe('OrganizationServiceApi', function() {
      describe('organizationServiceCreateOrganization', function() {
        it('should call organizationServiceCreateOrganization successfully', function(done) {
          // TODO: uncomment, update parameter values for organizationServiceCreateOrganization call and complete the assertions
          /*
          var body = new Systemproto.V1Organization();
          body.id = "";
          body.name = "";
          body.users = [new Systemproto.V1User()];
          body.users[0].id = "";
          body.users[0].name = "";
          body.users[0].organizationId = "";

          instance.organizationServiceCreateOrganization(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Systemproto.V1Organization);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            {
              let dataCtr = data.users;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Systemproto.V1User);
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("");
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("");
                expect(data.organizationId).to.be.a('string');
                expect(data.organizationId).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('organizationServiceDeleteOrganization', function() {
        it('should call organizationServiceDeleteOrganization successfully', function(done) {
          // TODO: uncomment, update parameter values for organizationServiceDeleteOrganization call and complete the assertions
          /*
          var id = "id_example";
          var opts = {};
          opts.name = "name_example";

          instance.organizationServiceDeleteOrganization(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Systemproto.V1Organization);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            {
              let dataCtr = data.users;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Systemproto.V1User);
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("");
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("");
                expect(data.organizationId).to.be.a('string');
                expect(data.organizationId).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('organizationServiceGetOrganization', function() {
        it('should call organizationServiceGetOrganization successfully', function(done) {
          // TODO: uncomment, update parameter values for organizationServiceGetOrganization call and complete the assertions
          /*
          var id = "id_example";
          var opts = {};
          opts.name = "name_example";

          instance.organizationServiceGetOrganization(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Systemproto.V1Organization);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            {
              let dataCtr = data.users;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Systemproto.V1User);
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("");
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("");
                expect(data.organizationId).to.be.a('string');
                expect(data.organizationId).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('organizationServiceUpdateOrganization', function() {
        it('should call organizationServiceUpdateOrganization successfully', function(done) {
          // TODO: uncomment, update parameter values for organizationServiceUpdateOrganization call and complete the assertions
          /*
          var body = new Systemproto.V1Organization();
          body.id = "";
          body.name = "";
          body.users = [new Systemproto.V1User()];
          body.users[0].id = "";
          body.users[0].name = "";
          body.users[0].organizationId = "";

          instance.organizationServiceUpdateOrganization(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Systemproto.V1Organization);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            {
              let dataCtr = data.users;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Systemproto.V1User);
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("");
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("");
                expect(data.organizationId).to.be.a('string');
                expect(data.organizationId).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
