/*
 * system.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Systemproto);
  }
}(this, function(expect, Systemproto) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Systemproto.UserServiceApi();
  });

  describe('(package)', function() {
    describe('UserServiceApi', function() {
      describe('userServiceCreateUser', function() {
        it('should call userServiceCreateUser successfully', function(done) {
          // TODO: uncomment, update parameter values for userServiceCreateUser call and complete the assertions
          /*

          instance.userServiceCreateUser(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Systemproto.V1User);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userServiceDeleteUser', function() {
        it('should call userServiceDeleteUser successfully', function(done) {
          // TODO: uncomment, update parameter values for userServiceDeleteUser call and complete the assertions
          /*
          var opts = {};

          instance.userServiceDeleteUser(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Systemproto.V1User);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userServiceGetUser', function() {
        it('should call userServiceGetUser successfully', function(done) {
          // TODO: uncomment, update parameter values for userServiceGetUser call and complete the assertions
          /*
          var opts = {};

          instance.userServiceGetUser(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Systemproto.V1User);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userServiceUpdateUser', function() {
        it('should call userServiceUpdateUser successfully', function(done) {
          // TODO: uncomment, update parameter values for userServiceUpdateUser call and complete the assertions
          /*

          instance.userServiceUpdateUser(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Systemproto.V1User);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
